site_name: POO en Java

docs_dir: 'md'

site_dir: 'docs'
nav:
  - Inicio: index.md
  - ¿Que es POO?: introduccion.md
  - Creación de clases: 
    - Clases: clases.md
    - Atributos: atributos.md
    - Metodos: metodos.md
  - Herencia: herencia.md
  - Enums e Interfaces: 
    - Enums: enums.md
    - Interfaces: interfaces.md
  - Excepciones: excepciones.md
  - FaQ: faq.md

theme: 
  name: material
  favicon: img/favicon.ico
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-3
        name: Switch to light mode

      features:
      - content.code.copy 
      - content.code.select
      - content.code.annotate
      - navigation.top

markdown_extensions:
  - admonition

extra_css: 
  - css/extra.css

plugins:
  - search